services:
  app:
    build: .
    container_name: chatbot_consumer_app
    env_file:
      - ./.env
    networks:
      - chatbot_corretora 
      - default
    restart: unless-stopped 

  mongo:
    image: mongo:latest
    container_name: mongo_db_chatbot
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - default 
networks:
  chatbot_corretora:
    external: true 
  default:
    driver: bridge

volumes:
  mongodata: