# docker-compose.yml
version: '3.8'

services:
  # Serviço da sua aplicação Python
  app:
    build: .
    container_name: chatbot_consumer_app # Mudei o nome para ser mais específico
    # REMOVIDO: depends_on, pois o RabbitMQ agora é externo
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Serviço do MongoDB (PODE SER REMOVIDO TAMBÉM SE FOR EXTERNO)
  mongo:
    image: mongo:latest
    container_name: mongo_db_chatbot # Nome específico
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: